### PR TITLE
Add functions getFormFields and getFormLayout

### PR DESCRIPTION
**Pull request by yhirochick**
以下の点修正しました｡

- "fields.json""layout.json" のAPI使う関数に変更
- 運用環境､テスト環境ごとにURLを使い分ける

修正してほしいところなどあればまた教えてください｡

### CODE REVIEW

**Comment by yhirochick** [comment]
@dtduc91 
Thanks for review!
I 'll fix comments.Sorry.

**Comment by yhirochick** [comment]
@dtduc91 
I Fixed comment.
Would you check the comment that I added to  66eb9d589b99ebfc42a974b4df68739125768d7b[#commitcomment-25125903](https://github.com/yhirochick/kintoneUtility/commit/66eb9d589b99ebfc42a974b4df68739125768d7b#commitcomment-25125903) about `params.isGuest` .

**Comment by dtduc91** [comment]
@yhirochick 
Currently, I think `params.isGuest` might be keep, because the affect scope is wide.
But in next maintain, we should consider about that.
 I prefer have a function which auto detect guest space in the SendRequest.js.

BTW: Your pull is good now. I will inform to merge.

**Comment by yhirochick** [comment]
@dtduc91 
I understood now.
It's issue about not only this PR but also another function.
Thank you for review!

**Comment by sada-nishio** [comment]
@yhirochick 
Thanks your contribution!
I'll merge this pull request :)

**Comment by yhirochick** [comment]
@sada-nishio 
Thank you for mergeing!

**Pull request merged**
